services:
  appdb1:
    profiles: ["appdb", "om"]
    build:
      context: .
      dockerfile: appdb.Dockerfile
    image: appdb:8.2
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    container_name: appdb1
    hostname: appdb1
    environment:
      - TZ=Asia/Seoul
    command:
      [
        "--replSet",
        "omrs",
        "--auth",
        "--bind_ip_all",
        "--keyFile",
        "/var/lib/mongo/rsAuthKey",
      ]

  appdb2:
    profiles: ["appdb", "om"]
    depends_on:
      - appdb1
    image: appdb:8.2
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    container_name: appdb2
    hostname: appdb2
    environment:
      - TZ=Asia/Seoul
    command:
      [
        "--replSet",
        "omrs",
        "--auth",
        "--bind_ip_all",
        "--keyFile",
        "/var/lib/mongo/rsAuthKey",
      ]

  appdb3:
    profiles: ["appdb", "om"]
    depends_on:
      - appdb2
    image: appdb:8.2
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    container_name: appdb3
    hostname: appdb3
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./conf:/var/lib/mongo/conf:ro
    entrypoint: ["/var/lib/mongo/conf/appdb_provision.sh"]
    command:
      [
        "/bin/python3",
        "/usr/local/bin/docker-entrypoint.py",
        "--replSet",
        "omrs",
        "--auth",
        "--bind_ip_all",
        "--keyFile",
        "/var/lib/mongo/rsAuthKey",
      ]

  om:
    profiles: ["om"]
    platform: linux/amd64
    build:
      context: .
      dockerfile: om.Dockerfile
    depends_on:
      - appdb3
    image: opsmanager:8
    deploy:
      resources:
        reservations:
          cpus: "4.0"
          memory: 15G
    container_name: om
    hostname: om
    environment:
      - TZ=Asia/Seoul
    ports:
      - 8080:8080
    user: "mongodb-mms:mongodb-mms"
    entrypoint:
      ["/bin/bash", "-c", "/etc/init.d/mongodb-mms start && sleep infinity"]

  ag1:
    profiles: ["agent"]
    build:
      context: .
      dockerfile: agent.Dockerfile
      args:
        - mmsGroupId=${mmsGroupId}
        - mmsApiKey=${mmsApiKey}
    image: om-agent:8
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 5G
    container_name: ag1
    hostname: ag1
    privileged: true
    environment:
      - TZ=Asia/Seoul
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1
    entrypoint: ["/opt/mongodb-mms-automation/agent_start.sh"]

  ag2:
    profiles: ["agent"]
    depends_on:
      - ag1
    image: om-agent:8
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 5G
    container_name: ag2
    hostname: ag2
    privileged: true
    environment:
      - TZ=Asia/Seoul
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1
    entrypoint: ["/opt/mongodb-mms-automation/agent_start.sh"]

  ag3:
    profiles: ["agent"]
    depends_on:
      - ag2
    image: om-agent:8
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 5G
    container_name: ag3
    hostname: ag3
    privileged: true
    environment:
      - TZ=Asia/Seoul
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1
    entrypoint: ["/opt/mongodb-mms-automation/agent_start.sh"]

  bkst:
    profiles: ["agent", "backup"]
    image: appdb:8.2
    deploy:
      resources:
        reservations:
          cpus: "1.0"
          memory: 2G
    container_name: bkst
    hostname: bkst
    environment:
      - TZ=Asia/Seoul
    command: ["--bind_ip_all"]

networks:
  default:
    name: omdemo_network
